Error resolved while adding new contacts
 E/ContentProviderOperation: mType: 1, mUri: content://com.android.contacts/data, mSelection: null, mExpectedCount: null, mYieldAllowed: false, mValues: data1=Aakash2 data2=Aakash2 mimetype=vnd.android.cursor.item/name, mValuesBackReferences: raw_contact_id=0, mSelectionArgsBackReferences: null<br>
E/JavaBinder: *** Uncaught remote exception! (Exceptions are not yet supported across processes.)
java.lang.ArrayIndexOutOfBoundsException: asked for back ref 0 but there are only 0 back refs
at android.content.ContentProviderOperation.backRefToValue(ContentProviderOperation.java:393)<br><br>

Above error occurs while adding contacts because account is added like not added as it was added before it was given a wrong value in ContentProviderOperation's newInsert() function and also not contains backReference<br>